# Generated by Django 2.0.3 on 2018-04-01 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('link_video', models.URLField()),
                ('link_github', models.URLField()),
                ('link_itchio', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
