# Generated by Django 2.0.3 on 2018-04-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', help_text='This image will be used if no valid video exists.', upload_to='projects/project_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_itchio',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_video',
            field=models.URLField(blank=True),
        ),
    ]
