# Generated by Django 2.0.3 on 2018-04-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180401_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='This image will be used if no valid video exists.', upload_to='projects/project_images'),
        ),
    ]
