# Generated by Django 2.0.3 on 2018-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180401_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_thumbnail',
            field=models.ImageField(blank=True, upload_to='projects/project_images'),
        ),
    ]
