# Generated by Django 2.0.3 on 2018-04-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180401_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_thumbnail',
            new_name='thumbnail',
        ),
    ]
