# Generated by Django 2.0.3 on 2018-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20180401_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link_video',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
