# Generated by Django 2.0.3 on 2018-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180403_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link_video',
        ),
        migrations.AddField(
            model_name='project',
            name='video_id',
            field=models.CharField(blank=True, help_text='Youtube video ID.', max_length=25),
        ),
    ]
