# Generated by Django 2.0.3 on 2018-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20180403_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Prefer a 1:1 ratio.', upload_to='projects/project_images'),
        ),
    ]
